FROM rust:1.94-slim

RUN apt-get update && apt-get install -y \
    pkg-config \
    libssl-dev \
    curl \
    git \
    build-essential \
    && rm -rf /var/lib/apt/lists/*
RUN rustup target add wasm32-unknown-unknown
RUN rustup toolchain install nightly
RUN rustup default nightly
RUN rustup target add wasm32-unknown-unknown --toolchain nightly
RUN cargo install cargo-leptos
WORKDIR /home/hkb/dev/Practice/leptos_test
COPY . .
CMD ["cargo", "leptos", "watch"]